# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
 dist: focal
 os: linux
 addons:
    packages:
    - libsndfile1-dev
    - fftw3-dev
    - libavfilter-dev
warnings_are_errors: true
cache: packages
r_packages: 
  - testthat
  - roxygen2
  - methods
after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::coveralls()'
