# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: required
warnings_are_errors: true
before_install:
- sudo add-apt-repository -y ppa:cran/ffmpeg-3
- sudo apt-get update
- sudo apt-get dist-upgrade
- sudo apt-get -qq update
- sudo apt-get install -y libsndfile1-dev
- sudo apt-get install -y fftw3-dev
- sudo apt-get install -y libavfilter-dev
cache: packages
r_packages: 
  - testthat
  - roxygen2
  - methods
after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::coveralls()'
